update to makefile

diff --git a/tests/entropy/SP800-90B_EntropyAssessment-master/cpp/Makefile b/tests/entropy/SP800-90B_EntropyAssessment-master/cpp/Makefile
--- a/tests/entropy/SP800-90B_EntropyAssessment-master/cpp/Makefile
+++ b/tests/entropy/SP800-90B_EntropyAssessment-master/cpp/Makefile
@@ -1,20 +1,18 @@
 ARCH ?= x86
 
-CXX ?= $(CROSS_COMPILE)g++
+CXX ?= $(CROSS_COMPILE) g++
 
 CXXFLAGS = -std=c++11 -fopenmp -O2 -ffloat-store -I/usr/include/jsoncpp
 ifeq ($(ARCH),x86)
 CXXFLAGS += -msse2 -march=native
 endif
 
-#CXX = clang++-15
-#CXXFLAGS = -g -Wno-padded -Wno-disabled-macro-expansion -Wno-gnu-statement-expression -Wno-bad-function-cast -fopenmp -O1 -fsanitize=address -fsanitize=undefined -fno-omit-frame-pointer -fdenormal-fp-math=ieee -msse2 -march=native -I/usr/include/jsoncpp
-#static analysis in clang using
-#scan-build-15 --use-c++=/usr/bin/clang++-15 make
 LIB = -lbz2 -lpthread -ldivsufsort -ldivsufsort64
 COND_LIB = -lmpfr -lgmp
 SHARED_LIB = -ljsoncpp -lcrypto
 INC =
+BIN_DIR = ../bin
+
 
 ######
 # Main operations
@@ -24,11 +22,20 @@ all:    iid non_iid restart conditioning transpose
 
 clean:
 	rm -f ea_iid ea_non_iid ea_restart ea_conditioning ea_transpose selftest/*.res
+	rm -f ${BIN_DIR}/*
+
+install:
+	@if [ ! -f ea_iid ] || [ ! -f ea_non_iid ] || [ ! -f ea_restart ] || [ ! -f ea_conditioning ] || [ ! -f ea_transpose ]; then \
+		echo "Error: Some executables are missing. Please run 'make' first."; \
+		exit 1; \
+	fi
+	mkdir -p $(BIN_DIR)
+	mv ea_iid ea_non_iid ea_restart ea_conditioning ea_transpose $(BIN_DIR)
 
 iid: iid_main.o
 iid_main.o: iid_main.cpp
 	$(CXX) $(CXXFLAGS) $(INC) iid_main.cpp -o ea_iid $(LIB) $(SHARED_LIB)
-	
+
 non_iid: non_iid_main.o	
 non_iid_main.o: non_iid_main.cpp
 	$(CXX) $(CXXFLAGS) $(INC) non_iid_main.cpp -o ea_non_iid $(LIB) $(SHARED_LIB)
